### PR TITLE
simple language switch

### PR DESCRIPTION
**Pull request by frudolph77**
Here is my very simple solution for a language switch.

The language is stored in a separate key in localStorage. I didn't want the language in the state object.

Maybe there are better ways to pass the language (state) to the cards. I only have basic React knowledge, and the state handling in React is a big black box for me at the moment.
Fell free to change it if necessary.

image
The dropdown for language selection is not visible during a game

All languages from turingmachine.info are implemented, ~~with the flaw that Español isn't working there. I have no idea how to fall back to English in this case~~.

There are more languages available than visible in the UI.
https://turingmachine.info/images/criteriacards/

### CODE REVIEW

**Comment by cpasoft** [comment]
Is this currently working? 
I have tried the URL https://alexander-zibert.github.io/turing-machine-board-game-solver/ and do not see this new option.

**Comment by frudolph77** [comment]
The pull request has not yet been merged. This is a upcoming feature that is not yet available online. Please be patient.

**Comment by cpasoft** [comment]
I thought it should be already working
No problem, no hurry. Thank you very much.

**Comment by frudolph77** [comment]
I've slightly updated the state handling for the language based on this article:
https://thomasderleth.de/keeping-react-state-and-local-storage-in-sync/

**Comment by frudolph77** [comment]
Please do not merge for the moment, I'll make some significant changes this evening.  

new_lang_switch

Just a preview, the language switch will be beside the icons later, and you will be able to switch the language anytime during playing.

**Comment by frudolph77** [comment]
revamped_lang_switch
That's the final solution, just decided to use an other source for the flag icons. On the first one the flags have all slightly different sizes and they just doesn't look good in the menu and I thought round icons will be more pleasing.

**Comment by cpasoft** [comment]
> ![revamped_lang_switch]On the first one the flags have all slightly different sizes and they just don't look good in the menu and I thought round icons will be more pleasing.

Beautiful!! ❤️

**Comment by cpasoft** [comment]
I don't know why, in Firefox the text is misaligned.
Here is in Edge:

And here is in Firefox:
imagen
imagen

And here is in Edge/chrome:
imagen
imagen

**Comment by frudolph77** [comment]
@cpasoft 
That's the pain with web development. Different browsers -> different rendering engines -> different results and to make it worse there could be differences on different OSes like Windows, MacOS and Linux.

I can't reproduce it in my environment, therefore I need your help. 
I think the problem is the scrollbar.
Please, open up `src/components/LanguageSelect.tsx` goto line 148 and change `min-width`  to `160px`.

image

If the text is still wrapped, increase the value for min-width.

**Comment by cpasoft** [comment]
> I can't reproduce it in my environment, therefore I need your help. I think the problem is the scrollbar. Please, open up `src/components/LanguageSelect.tsx` goto line 148 and change `min-width` to `160px`. Let me know the result.

Modified and works fine in both Firefox and Edge on Windows 10 and 11.

**Comment by alexander-zibert** [comment]
@frudolph77 This looks really good! Thank you!

**Comment by cpasoft** [comment]
> @frudolph77 This looks really good! Thank you!

Yes, it does.
I have tested your deployment and it fits perfectly, tested on Firefox, edge and chrome, and also on Android.
GREAT!!! :-)

**Pull request merged**
